function [means, errors] = buildMeansStd(df)
%BUILDMEANSSTD for the dataframe df, computes the average and standard
%deviation of each emotion

    %% Removing samples with NaN
    angry = df.F_Angry(~isnan(df.F_Angry));
    disgusted = df.F_Disgusted(~isnan(df.F_Disgusted));
    afraid = df.F_Afraid(~isnan(df.F_Afraid));
    happy = df.F_Happy(~isnan(df.F_Happy));
    sad = df.F_Sad(~isnan(df.F_Sad));
    surprised = df.F_Surprised(~isnan(df.F_Surprised));
    neutral = df.F_Neutral(~isnan(df.F_Neutral));
    
    %% Computing mean
    means = [mean(angry),...
             mean(disgusted),...
             mean(afraid),...
             mean(happy),...
             mean(sad),...
             mean(surprised),...
             mean(neutral)];
            
    %% Computing standard deviation
    errors = [std(angry),...
              std(disgusted),...
              std(afraid),...
              std(happy),...
              std(sad),...
              std(surprised),...
              std(neutral)];
end